CREATE TABLE FACULTY_STAFF (
    DISCOUNT_ID INTEGER PRIMARY KEY,
    PROVIDER_NAME VARCHAR2(200),
    DISCOUNT_NAME VARCHAR2(200),
    DIRECTIONS VARCHAR(1000), 
    DISCOUNT_TYPE VARCHAR2(200),
    FAVORITES BOOLEAN
);

CREATE TABLE STUDENTS (
    DISCOUNT_ID INTEGER PRIMARY KEY,
    PROVIDER_NAME VARCHAR2(200),
    DISCOUNT_NAME VARCHAR2(200),
    DIRECTIONS VARCHAR(1000),
    DISCOUNT_TYPE VARCHAR2(200),
    FAVORITES BOOLEAN
);

CREATE TABLE OTHERS (
    DISCOUNT_ID INTEGER PRIMARY KEY,
    PROVIDER_NAME VARCHAR2(200),
    DISCOUNT_NAME VARCHAR2(200), 
    DIRECTIONS VARCHAR(1000),
    DISCOUNT_TYPE VARCHAR2(200),
    FAVORITES BOOLEAN
);
